version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    groups:
      gha:
        patterns:
          - "*"
