name: Node.js CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Create release PR or tag release
        id: release
        uses: googleapis/release-please-action@v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

      - name: Setup Node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 26
          registry-url: "https://registry.npmjs.org"

      - name: Update npm to latest
        if: ${{ steps.release.outputs.release_created }}
        run: npm install -g npm@latest

      - name: Install third party dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Check for type errors
        if: ${{ steps.release.outputs.release_created }}
        run: npm run type

      - name: Publish to npm with provenance
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --tag latest --provenance --access public
