name: cd

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      nw-builder--release_created: ${{ steps.release.outputs['packages/nw-builder--release_created'] }}
      doctor--release_created: ${{ steps.release.outputs['packages/doctor--release_created'] }}
      getter--release_created: ${{ steps.release.outputs['packages/getter--release_created'] }}
      runner--release_created: ${{ steps.release.outputs['packages/runner--release_created'] }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - id: release
        uses: googleapis/release-please-action@v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

  publish-nw-builder:
    name: Publish nw-builder to npm
    needs: release-please
    if: ${{ needs.release-please.outputs.nw-builder--release_created }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm@latest

      - run: npm ci

      - run: npm publish --tag latest --provenance --access public --workspace=nw-builder

  publish-doctor:
    name: Publish @nwutils/doctor to npm
    needs: release-please
    if: ${{ needs.release-please.outputs.doctor--release_created }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm@latest

      - run: npm ci

      - run: npm run type --workspace=@nwutils/doctor

      - run: npm publish --tag latest --provenance --access public --workspace=@nwutils/doctor

  publish-getter:
    name: Publish @nwutils/getter to npm
    needs: release-please
    if: ${{ needs.release-please.outputs.getter--release_created }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm@latest

      - run: npm ci

      - run: npm run type --workspace=@nwutils/getter

      - run: npm publish --tag latest --provenance --access public --workspace=@nwutils/getter

  publish-runner:
    name: Publish @nwutils/runner to npm
    needs: release-please
    if: ${{ needs.release-please.outputs.runner--release_created }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm@latest

      - run: npm ci

      - run: npm run type --workspace=@nwutils/runner

      - run: npm publish --tag latest --provenance --access public --workspace=@nwutils/runner
