name: e2e

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-26
          - ubuntu-24.04
          - windows-2025
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Setup Volta
        uses: volta-cli/action@v5.0.0
      - name: Install third party dependencies
        run: npm ci
      - name: Check third party dependencies for vulnerabilities
        run: npm audit
      - name: Check for linting errors
        run: npm run lint
      - name: Check for testing errors
        run: npm run test:cov
        env:
          CI: true
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: coverage-${{ matrix.os }}
          path: coverage
      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.11.2
        with:
          name: Vitest Coverage (${{ matrix.os }})
          json-summary-path: coverage/coverage-summary.json
