on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
