name: security

jobs:
  codeql:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    steps:
      runs-on: ubuntu-24.04
      steps:
        - name: Init CodeQL
          uses: github/codeql-action/init@v3
          with:
            languages: ['javascript', 'typescript']
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v3
